blank_issues_enabled: false
contact_links:
  - name: How Do I Question related to Platform 
    url: https://learn.microsoft.com/en-us/answers/tags/339/office-teams-development
    about: Use Microsoft QnA for How Do I question use related to Platform
